sudo: false

language: python
python: 2.7

services:
    - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

env:
    - TOX_ENV=py27
    - TOX_ENV=py27-psycopg2cffi
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py35-psycopg2cffi
    - TOX_ENV=pypy
    - TOX_ENV=pypy-psycopg2cffi
    - TOX_ENV=docs
    - TOX_ENV=pep8

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
    irc: "irc.freenode.org#alchimia"
