sudo: false

language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: pypy
      env: TOX_ENV=pypy
    - python: 2.7
      env: TOX_ENV=docs
    - python: 2.7
      env: TOX_ENV=pep8

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

notifications:
    irc: "irc.freenode.org#alchimia"
