language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=docs
    - TOX_ENV=pep8

install:
    - pip install tox pbr

script:
    - tox -e $TOX_ENV

notifications:
    irc: "irc.freenode.org#alchimia"
